# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanliuyunapp', '0005_auto_20161106_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='编辑文档'),
        ),
    ]
